### ISSUE TITLE
Show Trending Streams Service

### ISSUE THREAD

**Issue by ericaddison** [ericaddison/APT_miniProject#12]

**Comment by psigourney** [comment]
Just found a bug in CronTrendsService.trending().... apparently it's not a good idea to add/remove elements from a list while you're iterating through it :)

When the view cleanup job runs, it's removing the stream view entries from the list as it iterates through the list... so I'll need to store the entries in a separate list and remove them after the loop completes.
I'll also create the /trending page today.

**Comment by ericaddison** [comment]
Seems like this is working well ... right @psigourney ?
