### ISSUE TITLE
Reverted Master

### ISSUE THREAD

**Issue by ericaddison** [ericaddison/APT_miniProject#15]
@psigourney @mspagon 
I reverted `master` back to the last common commit between the work that Patrick and I have been doing. Patrick, your previous version of master is stashed on a new branch called `patrick_master`. We need to utilize the "pull request" feature here on github, or have a better way of communicating when we want to update `master` so that we are all kept in the loop.

I strongly believe that we should not ever just "push" to `master`, but only "merge" into `master` after we have all agreed on the proposed changes (or at least had a chance to discuss it). Also, we should try hard to not introduce crashing code into `master`. I really think `master` should be treated as kind of sacred, like a common point of reference that we all feel OK (or at least informed) about...

SORRY that I'm being an ogre about this!

**Comment by psigourney** [comment]
Sorry.  Just saw this email. (after another push).

I'll stop work now.  Can you clean up whatever issues I've caused, then
I'll checkout again.

**Comment by ericaddison** [comment]
Sure thing. I'll try to incorporate the changes you made to the manage page but leave out the view stuff. Is that OK?

**Comment by psigourney** [comment]
Absolutely.
