### ISSUE TITLE
Define stream data model

### ISSUE THREAD

**Issue by ericaddison** [ericaddison/APT_miniProject#2]
and python class implementations

**Comment by ericaddison** [comment]
@psigourney @mspagon 
I'm going to take a stab at this... 
I am thinking of thin, dumb `stream` objects that pretty much just contain a list of `stream_item` objects, which themselves are just URLs plus meta-data. 

I see maybe three primary data models to think through:
- A Stream of pictures (or allow extensibility for other media types)
- Pictures in a stream
- Users

After that I think any additional data will be the result of operations on these models. I would think of creating corresponding Python classes that look like:
- `Stream`
- `StreamItem` (or `Stream_Item`, whatever the right convention is)
- `User`
- other methods to perform operations on these types

**Comment by ericaddison** [comment]
I also liked the Jinja templating we used in the AppEngine tutorial. Seems like a clean way to separate the View part away from model/controller stuff...

**Comment by psigourney** [comment]
Oh,  a 'stream' is just a photo album.  With subscribers and tags.  
Gonna make the data model using the assumption that a picture can only belong to a single stream/album.

Here's a first pass

Users
--------
ID (PK)
Name
Password (just storing passwords in plaintext)

Streams (ie: Photo albums)
-------------------------------
ID (PK)
UserID (FK)
Name
CoverImage (URL to image)
NumberOfViews

StreamItems (ie: Pictures)
----------------------------------
ID (PK)
StreamID (FK)
Name
Image (datatype: blob, the actual image file)
DateAdded

Tags
---------------
ID (PK)
Name

StreamTags
------------------
ID (PK)
StreamID (FK)
TagID (FK)


StreamSubscribers
-------------------------
ID (PK)
StreamID (FK)
UserID (FK)

**Comment by psigourney** [comment]
Here's the DDL to create the tables in MySQL. (assuming "db" is the schema name)

[create_tables.txt](https://github.com/ericaddison/APT_miniProject/files/1326714/create_tables.txt)

**Comment by ericaddison** [comment]
@psigourney 
Nice! I'm not positive that we will have a MySql DB available in GAE under the free options... I think, for free, we can use the Google Cloud Datastore, which looks like it stores JSON-like objects...

What is your impression about that part so far?

**Comment by psigourney** [comment]
Data model using ndb:
[datamodel.txt](https://github.com/ericaddison/APT_miniProject/files/1333733/datamodel.txt)

Not sure about how to go about integrating Users with these models, but in the Guestbook demo, they stored "Author" as a string for identity and a string for email.  So I figure we can just omit the Users table altogether and just store the user email into the 'user' fields for Stream and StreamSubscriber.

**Comment by ericaddison** [comment]
@psigourney 
Well that's cool! I'll need a minute to absorb the interactions we'll have between these objects...

I might feel better if we still had a `user` property, and use a `userID` field as a key that is stored in the other properties. (That way we wouldn't haaaave to rely on Google login...) Could we do something like this?
```python
class Stream(ndb.Model):
    streamID = ndb.IntegerProperty(indexed=True)
    userID = ndb.IntegerProperty(indexed=True)
    name = ndb.StringProperty(indexed=False)
    coverImageURL = ndb.StringProperty(indexed=False)
    numViews = ndb.IntegerProperty(indexed=False)

class StreamItem(ndb.Model):
    streamID = ndb.IntegerProperty(indexed=True)
    name = ndb.StringProperty(indexed=False)
    image = ndb.BlobProperty(indexed=False)
    dateAdded = ndb.DateProperty(indexed=False)

class Tag(ndb.Model):
    tagID = ndb.IntegerProperty(indexed=True)
    name = ndb.StringProperty(indexed=False)

class StreamTag(ndb.Model):
    streamID = ndb.IntegerProperty(indexed=True)
    tagID = ndb.IntegerProperty(indexed=True)

class StreamSubscriber(ndb.Model):
    streamID = ndb.IntegerProperty(indexed=True)
    userID = ndb.IntegerProperty(indexed=True) 

class StreamUser(ndb.Model):
    userID = ndb.IntegerProperty(indexed=True)
    firstName = ndb.StringProperty(indexed=False)
    lastName = ndb.StringProperty(indexed=False)
    email = ndb.StringProperty(indexed=False)
```

**Comment by ericaddison** [comment]
@psigourney 
I haven't done the storage tutorial yet (oh no!), but one thing I wonder is if, when you store a `StructuredProperty` within a property, does it keep a reference to an existing property or make a copy?

**Comment by psigourney** [comment]
I'm just guessing here, but I think it would be a pointer to an existing
object.  So if the Author record (entity?) gets updated, when
Greeting.author is read, it would display the updated value.

**Comment by ericaddison** [comment]
OK, if that turns out to be the case then I would probably go back on some of my suggestions and make it look more like what you had :)

I would still like to have our own `StreamUser` class though. Is that OK?

**Comment by psigourney** [comment]
I'm gonna go back and revisit the model... I think there might be some tricks I can do that I'm not catching in order to link the tables to each other.  There's some Ancestor/Parent thing that might make the queries/relationships easier.

**Comment by ericaddison** [comment]
Cool. I'm gonna play with it some as well...

**Comment by ericaddison** [comment]
Ok, here is an interesting point:
We get a unique integer ID key for free with every item that you put into the database! So there is no need for our types to store their own ID keys... 

On the other hand, we can also manually specify the unique key for any object as well, so we can easily have users stored uniquely by email, or by google user ID, or whatever.

That info is all here: https://cloud.google.com/datastore/docs/concepts/entities

With that, I think our data scheme could be:
```python
class Stream(ndb.Model):
    userID = ndb.IntegerProperty(indexed=True)
    name = ndb.StringProperty(indexed=False)
    coverImageURL = ndb.StringProperty(indexed=False)
    numViews = ndb.IntegerProperty(indexed=False)

class StreamItem(ndb.Model):
    streamID = ndb.IntegerProperty(indexed=True)
    name = ndb.StringProperty(indexed=False)
    image = ndb.BlobProperty(indexed=False)
    dateAdded = ndb.DateProperty(indexed=False)

class Tag(ndb.Model):
    name = ndb.StringProperty(indexed=False)

class StreamTag(ndb.Model):
    streamID = ndb.IntegerProperty(indexed=True)
    tagID = ndb.IntegerProperty(indexed=True)

class StreamSubscriber(ndb.Model):
    streamID = ndb.IntegerProperty(indexed=True)
    userID = ndb.IntegerProperty(indexed=True) 

class StreamUser(ndb.Model):
    firstName = ndb.StringProperty(indexed=False)
    lastName = ndb.StringProperty(indexed=False)
    email = ndb.StringProperty(indexed=False)
```

**Comment by psigourney** [comment]
ndb.ReferenceProperty was the type that I was missing.  It allows you to do relations between the object types.

so for Stream,  the userID would be a ReferenceProperty to an instance of StreamUser.

https://cloud.google.com/appengine/articles/modeling

I've made changes to the model in my branch, but I'm not able to push to github due to the firewall here at work, so I'll push once I get home.

**Comment by ericaddison** [comment]
OK then! In that case, should we think again about just maintaining lists within the entities?

For example, instead of having the `StreamTag` type, which we would ostensibly query either for a particular `tagID` or `streamID`, should we instead maintain a list of `Tags` within each `Stream` entity, and a dual list of `Streams` within each `Tag` entity? That would cut down on database queries, I think, and not require any additional storage.

**Comment by ericaddison** [comment]
Oh but wait a minute ... maybe it looks like `ReferenceProperty` was part of the old "DB" API, and the current API is "NDB". Maybe we need to look at the `KeyProperty` type?

Also I take back my previous comments about the lists of properties. I really like how clean your design is with the `StreamTag` and `StreamSubscriber`. I would suggest the following tweak for the model:

```python
class Stream(ndb.Model):
    owner = ndb.KeyProperty(indexed=True, type='StreamUser')
    name = ndb.StringProperty(indexed=False)
    coverImageURL = ndb.StringProperty(indexed=False)
    numViews = ndb.IntegerProperty(indexed=False)

class StreamItem(ndb.Model):
    stream = ndb.KeyProperty(indexed=True, type='Stream')
    name = ndb.StringProperty(indexed=False)
    image = ndb.BlobProperty(indexed=False)
    dateAdded = ndb.DateProperty(indexed=False)

class Tag(ndb.Model):
    name = ndb.StringProperty(indexed=False)

class StreamTag(ndb.Model):
    stream = ndb.KeyProperty(indexed=True, type='Stream')
    tag = ndb.KeyProperty(indexed=True, type='Tag')

class StreamSubscriber(ndb.Model):
    stream = ndb.KeyProperty(indexed=True, type='Stream')
    user = ndb.KeyProperty(indexed=True, type='StreamUser') 

class StreamUser(ndb.Model):
    firstName = ndb.StringProperty(indexed=False)
    lastName = ndb.StringProperty(indexed=False)
    email = ndb.StringProperty(indexed=False)
```

Then to get all streams for a tag, for example, we could do something like:

```python
some_tag = get_a_tag_somehow()
streams = StreamTag.query(StreamTag.tag == some_tag.key).fetch()
```

And we are just using the already-present key value of the entities.

https://cloud.google.com/appengine/docs/standard/python/ndb/entity-property-reference
https://cloud.google.com/appengine/docs/standard/python/ndb/db_to_ndb

**Comment by psigourney** [comment]
I hate nbd.  Let's forget the whole Reference Key thing and just store the values as strings.

**Comment by ericaddison** [comment]
Oh man! Is it giving you trouble or are you just ready to move on? I'm gonna play with our models tonight.

**Comment by psigourney** [comment]
On the manage page, when the user's streams are listed, the stream.name
would be fine, but stream.user would return the key to the StreamUser
object.  Tried a couple different ways to try to resolve that key into the
actual StreamUser object (so the name/email values could be displayed), but
I'm not seeing it.

**Comment by mspagon** [comment]
I know you both have talked about this already, but I need confirmation on my understanding of **StreamTag** here...  I don't want to change anything at this point, just understanding.

```python
class Tag(ndb.Model):
    name = ndb.StringProperty(indexed=False)

class StreamTag(ndb.Model):
    stream = ndb.KeyProperty(indexed=True, type='Stream')
    tag = ndb.KeyProperty(indexed=True, type='Tag')
```

When I have two streams with the following tags:
1) Bob's Burgers
    -Food
    -Burgers
2) Kathy's Deli
    -Food
    -Sandwhices

We have FOUR streamkeys.
1) Bob's Burgers/Food
2) Bob's Burgers/Burgers
3) Kathy's Deli/Food
4) Kathy's Deli/Sandwhiches

We made this decision to allow for easy querying in both directions????

**Comment by psigourney** [comment]
It was the old relational-database design where a normalized field can only
contain a single value.

With this data store, you have repeated values, so on the Streams entity
you can have 'Tags = ndb.StringProperty(repeated=True)', and have a list of
tags for that String.

tagSearch = 'Food'
Streams.query(Stream.tags == tagSearch).fetch()

**Comment by ericaddison** [comment]
Yeah @mspagon, it allows for easy querying in both directions. We weren't sure if there was a way to easily do that using the repeated properties, except for storing **two** sets of repeated properties, i.e. a `Stream` stores a list of `Tags` and a `Tag` stores a list of `Streams`... That seems messier to me! Plus this has the ease of deletion as well: easier and more efficient to delete a single entity when removing a `Tag` from a `Stream` than it is to update two separate lists.

The `StreamItem`, on the other hand, has a different relationship with `Stream`, so we are currently storing that as a `repeated` property within `Stream`. It seems less likely, or even non-sensical, to query for all the `Streams` associated with a given `StreamItem`. There should just be one, right?

**Comment by mspagon** [comment]
1) Ok I like it!

2) Could you elaborate on your vision of the project structure with regards to services? Like why is some code written in services and some written in Main.py?  I'm confused and sense an inconsistency between @psigourney and @ericaddison in terms of where we are writing code and I just want to try to be consistent in my efforts.

3)  I also really admire your admin page.  (was this a requirement?)  With regards to "ViewAll" streams - You have already implemented this in the admin page and understanding the services hierarchy will let me utilize them in creating ViewAll.

Thanks!!!!

**Comment by ericaddison** [comment]
@mspagon sure! Let's talk about that in #23 

@psigourney Wait! Does that kind of query for repeated properties work??? That is, will `Stream.query(Stream.tags == a_tag.key).fetch()` return all the `Streams` that contain the requested `Tag`? Is that what you were trying to tell me all along??? That would certainly solve the two-way search problem I keep rambling about... Still the two-list issue though, and atomicity/transaction/whatever nonsense I think? Maybe?

**Comment by psigourney** [comment]
>> Wait! Does that kind of query for repeated properties work??? That is,
will Stream.query(Stream.tags == a_tag.key).fetch() return all the Streams
that contain the requested Tag? Is that what you were trying to tell me all
along??? That would certainly solve the two-way search problem I keep
rambling about... Still the two-list issue though, and
atomicity/transaction/whatever nonsense I think? Maybe?

From what I remember (it was last week), it will.  If you have a repeated
attribute Stream.tags, then doing a query on  "== one_tag" will return all
matches where the one_tag is present in the tags list.

**Comment by ericaddison** [comment]
Well, that was my _primary_ issue with that approach... If you feel like changing the model (again that is, since I shouted you down last time!), I'm willing to cooperate! If we DO, I think we should right away write helper methods for each class that perform the actual database accesses... That's something we probably should have done early on, but we were too busy learning wtf we were even doing here :)

We don;t HAVE to do this, but just as a suggestion, I'm thinking something like:
```python
# in a new file Stream_Model.py, or Model_Stream.py, or something
class Stream(ndb.Model):
    owner = ndb.KeyProperty(indexed=True, kind='StreamUser')
    name = ndb.StringProperty(indexed=False)
    # more fields...

    @classmethod
    def get_streams_by_owner(cls, ownerID):
        # do the appropriate DB calls here...
        # return a list of stream objects

    @classmethod
    def get_streams_by_tag(cls, tagName):
        # return list of stream objects

    # etc. Other queries
```
And then we would never actually call `ndb` anywhere in our code except in these `Model` classes! Just to make more work for ourselves, I think each of these python methods should have an associated "service", i.e. a URL we can navigate to that returns the same information in a JSON string. Then it is platform independent, and we could write a C program that interacts with our app if we wanted :)

**Comment by ericaddison** [comment]
I think it's time to close this one... :)
