### ISSUE TITLE
Phase1 WebUI work distribution

### ISSUE THREAD

**Issue by ericaddison** [ericaddison/APT_miniProject#3]

**Comment by ericaddison** [comment]
After @mspagon and I chatted last night, we devised the following tasks for us to work on for next week:

### Everyone:
- Implement a login page with google account
- Understand our current data models
- Review the suggested exercises for sending mail and cloud storage
- Review Jinja for HTML templating

We need to implement 7 services related to the app. Split up as:
- Management		Eric
- create a stream		Michael
- view a stream		Patrick
- image upload		Eric
- view all streams		Michael
- search streams that contain matching text	Patrick
- show trending streams 	Whoever gets there first :)

### Goal for next Friday (9/29):
- Data model implemented in python
- login page done
- Good plan and/or start on services
- Review exercises complete

### Note:
	Eric is putting practice webapps in a repo here: https://github.com/ericaddison/appengine_samples


Meet again next Friday … 8:00 phone call Google Hangouts

**Comment by psigourney** [comment]
Google Sign-in service (to create login pages which use Google accounts):

https://developers.google.com/identity/sign-in/web/
https://developers.google.com/identity/sign-in/web/sign-in

I created the Google credentials for the project:

Client ID: 567910868038-rj3rdk31k9mbcf4ftder0rhfqr1vrld4.apps.googleusercontent.com

**Comment by ericaddison** [comment]
@psigourney 
Since you are working on the manage service, should I take the "view stream" service from you?

**Comment by psigourney** [comment]
Yeah, you can take View.
