### ISSUE TITLE
Error when submit upload with no file chosen

### ISSUE THREAD

**Issue by ericaddison** [ericaddison/APT_miniProject#32]
yup... I need to fix it :)

**Comment by ericaddison** [comment]
Also if you don't refresh and get a stale upload link...

**Comment by ericaddison** [comment]
Javascript can probably help here as well. As in, button not enabled until a file is chosen.

**Comment by mspagon** [comment]
Great Idea! for the time being maybe we can have it do nothing?

**Comment by ericaddison** [comment]
This is taken care of from the server side.
