### ISSUE TITLE
Notes from 10/4/17

### ISSUE THREAD

**Issue by ericaddison** [ericaddison/APT_miniProject#38]
- Form for trending email interval (Patrick)
- Checkboxes on management page for delete/unsubscribe (Eric)
- View all page (Michael)
- ~~Error page that takes an error message as a GET parameter (Michael)~~ ( #42 )
- ~~Finish text search (Eric)~~ (currently ready in PR #40)
- Address bugs (All)

**Comment by mspagon** [comment]
I have no experience with specifying GET parameters in URLs....

> Error page that takes an error message as a GET parameter (Michael)

So a get parameter is specified by http://www.url.com?param1=value1&param2=value2 delimited by '&'?

So until I find a specific convention online I will do:
http://www.url.com/error?code=100&code=200 and we will have a case/switch statement with strings associated for the string to display?

**Comment by mspagon** [comment]
Ok I am going to do some reading on urllib and urllib2 and httplib

**Comment by ericaddison** [comment]
I think we hit everything on the list :D
