### ISSUE TITLE
StreamsOwned and StreamsSubbed aren't correct

### ISSUE THREAD

**Issue by psigourney** [ericaddison/APT_miniProject#47]
When I create a stream, regardless of whether I put a subscriber or not, the stream shows up as owned and subscribed by me.  Also, adding other emails to the subscriber list does not result in the stream being subscribed by that user.

**Comment by psigourney** [comment]
Fixed it.

Had copied a FOR block from the owned_streams code without changing the list it was iterating through.

**Comment by ericaddison** [comment]
lol! I just fixed that as well... Lets see what conflicts I get on my branch! :)
