### ISSUE TITLE
Sending Trending Emails

### ISSUE THREAD

**Issue by psigourney** [ericaddison/APT_miniProject#55]
I updated the email message to include HTML (hopefully it will be rendered when the email is sent, rather than displaying as HTML code).

Also went into the app engine settings and added myself as an "authorized email sender", and set my email address as the 'from" address.  After the next deploy, I'm interested in whether the email will be sent.  If not, I'll have to dig some more into the issue.

**Comment by psigourney** [comment]
Just got a "normal" trending email!!

So the address change wasn't needed.  I changed the address back to the original one.

Next deploy of master should push out the message body changes so we can see whether the content is pretty or just a bunch of code.

**Comment by ericaddison** [comment]
ah ok, cool! @mspagon, lets make sure we pull those changes from master.

**Comment by ericaddison** [comment]
This seems to be working well. Great email format, @psigourney !
