### ISSUE TITLE
Search does not return anything

### ISSUE THREAD

**Issue by mspagon** [ericaddison/APT_miniProject#58]
I'm searching for "food" when two of my streams have the food tag.  Nothing is returning.

However the search returns the stream titled "Bob's burgers" when I search for "bob".

**Comment by ericaddison** [comment]
@mspagon 

I think those particular tags were left over from before an update to the search index. I removed the tags "food", "bob", and "burgers" from your streams, then re-added them, and now I see them in the search...

Can you confirm?

**Comment by ericaddison** [comment]
@psigourney 
On the same note, the tags in your stream are kind of "stuck"... can you delete and recreate your stream?

Thanks!

**Comment by ericaddison** [comment]
@psigourney 
@mspagon 
Also, new version is all lower case tags ... all converted to lower case
