### ISSUE TITLE
GeoMap - lat/long stored as None

### ISSUE THREAD

**Issue by psigourney** [ericaddison/APT_miniProject#69]
Odd issue... I updated Service_UploadFile.py to include loading the Latitude and Longitude of an image.  I've even added print statements to the POST function and the parameters are loading correctly.  BUT.... when I add an image with lat/long values, when I check the image in the datastore, the values are stored as 'None'.

This is on the patrick_geomap branch.

**Comment by ericaddison** [comment]
Can you start a pull request so we can make handy comments on the code?

**Comment by psigourney** [comment]
Found it.  It was the 'create' function within NdbClasses.py that also needed to have lat/lng added to it.

**Comment by ericaddison** [comment]
Good catch :)
