### ISSUE TITLE
Create Stream Service

### ISSUE THREAD

**Issue by ericaddison** [ericaddison/APT_miniProject#7]

**Comment by ericaddison** [comment]
@mspagon 
We need this one in place. Are you still OK with it or should I take care of it?

**Comment by mspagon** [comment]
I will post an update by 8 AM if that is okay.

**Comment by mspagon** [comment]
Added Pull Request: #27 .

As quoted from the Pull Request comments:
> The create stream service remained the same:
> 1)Posts the form info to the data store.
> 2) redirects to /viewstream?streamID={}
> 
> I lack big picture understanding... I wanted to confirm that there is no need to create a JSON of any information for further steps? I have not added that functionality.

**Comment by ericaddison** [comment]
Updated in PR #30
