### ISSUE TITLE
Better file upload

### ISSUE THREAD

**Issue by mspagon** [ericaddison/APT_miniProject#72]
I suspect that I will need help figuring out and at least discussing this.

I created a branch: [better_file_upload](https://github.com/ericaddison/APT_miniProject/tree/better_file_upload)

It is very simple.  I just added dropzone.css and dropzone.js to the project and added a <script></script> statement into the bottom of viewstream.html

The old image upload form is left in place for testing purposes.

--------------------------------------------------
The viewstream.html dropzone uploader is able to upload the FIRST image of multiple selected.  I'm guessing we have to somehow create a for loop and iterate over each of them.

I'm getting caught up on understanding the file upload service/handler at the moment.

(DROPZONE is quite different from the jquery-file-uploader so maybe one is easier for you to understand.  I had more success with dropzone)  I couldn't understand the javascript templating that came along with the jquery-file-uploader, but the jquery-file-uploader seems more modular and easier to configure and well documented.

**Comment by mspagon** [comment]
i'll be breaking down the .js script at work and report back.

**Comment by mspagon** [comment]
This looks like a pretty clear resource for the jquery uploader.  I will give this a shot.

> To upload files to the Blobstore of Google App Engine with the File Upload plugin, you implement a normal form-based file upload on server-side and then adjust it to return a JSON response.

>First, you can follow Google's documentation on Blobstore File Uploads. Then, instead of redirecting the user to the uploaded blob, redirect to a page that returns a JSON response with an array of objects with information for each uploaded file (see Setup guide).

https://github.com/blueimp/jQuery-File-Upload/wiki/Google-App-Engine

**Comment by ericaddison** [comment]
@mspagon 
Thanks! I'll take a look at this branch tonight.

**Comment by mspagon** [comment]
Looking further at JQuery-file-uploader I noticed this weird thing that complicates understanding it for me:  The demo is hosted on github but the files are being uploaded to app-engine.  Also still can't get the javascript templating working.  Going to go back to this branch and look at Dropzone a little more.

[Cross-Domain Uploads](https://github.com/blueimp/jQuery-File-Upload/wiki/Google-App-Engine#app-engine-blobstore-and-cross-domain-uploads):

> Since I've rewritten the demo to be hosted on Github pages while the uploads are still done to App Engine, I've had to tackle the Cross-Domain Blobstore issue.

**Comment by mspagon** [comment]
@ericaddison 

This branch inconsistently uploads up to two files, usually only one, out of many.  We get an error that says 
![image](https://user-images.githubusercontent.com/5027451/31413738-7477e9e4-ade0-11e7-9090-813b0573799d.png)

We somehow need to generate a new upload link for each image, [this](https://stackoverflow.com/questions/4762779/how-to-upload-multiple-files-to-blobstore) stackoverflow post is helpful.

**Comment by mspagon** [comment]
We have to generate a separate upload_url for EACH image we plan on uploading.

The way we have our code set up now we generate one SINGLE upload URL then pass that to the HTML template.  So I tried creating a list of 10 or so blob store URLS and then pass all 10 to the HTML form and tried to create an AJAX call that would create 10 POST calls using each unique URL.  Not having any luck so far.

It would be easier if the code was set up in reverse to have the HTML form pass a list of file name.  And have python then generate the blob_store url after the fact.  I'm just really confused.

Sorry guys, there's just so much code all over the place I'm not really understanding it all at this point.  Hope it will be easier starting fresh on Android.

Still gonna keep trying.

**Comment by ericaddison** [comment]
Check out the new commit in the open PR #73 for your branch. It configures the uploader to multiple files can go up on a single upload URL.
