### ISSUE TITLE
Parameters in Javascript

### ISSUE THREAD

**Issue by psigourney** [ericaddison/APT_miniProject#74]
Having issues with formatting parameters in javascript.  I'm getting the single quotes as ascii: "&#39;"
Tried using replace, but the script choked on the 'var locations' line:

Code:

            function initMap() {                
                var locations = {{ streamItemsLoc }};
                locations = locations.replace("&#39;", "");

Debugger output:

            function initMap() {                
                var locations = [[&#39;6149602893889536&#39;, datetime.datetime(2017, 10, 10, 12, 20, 0, 142528), &#39;http://localhost:8080/_ah/img/V6q8N9D-tThJan17B11dgw==&#39;, &#39;30.42039&#39;, &#39;-97.7046206&#39;], [&#39;6149602893889536&#39;, datetime.datetime(2017, 10, 10, 1, 58, 56, 701893), &#39;http://www.lolcats.com/images/u/07/29/lolcatsdotcomug9elgxemb1avrt1.jpg&#39;, &#39;30.2893746&#39;, &#39;-97.7349663&#39;]];
                locations = locations.replace("&#39;", "");

edit:  I can parse it to JSON before sending over, but then I get this instead, so it's no better.

    var locations = [[&quot;6149602893889536&quot;, &quot;2017-10-10 12:20:00&quot;,

**Comment by psigourney** [comment]
Nevermind.  Needed quotes around the variable:

    var locations = "{{ streamItemsLoc }}";

edit:  well, now it's a string instead of an array....

**Comment by psigourney** [comment]
ARGHGHGGH!!!!   Finally working:


            function initMap() {                
                var locationJSON = "{{ streamItemsLoc }}";
                locationJSON = locationJSON.replace(/&quot;/g, "\"");
                var locations = JSON.parse(locationJSON);

**Comment by ericaddison** [comment]
Oh man, is this for URL formatting? That stuff is so frustrating!

Have you had a look at [`encodeURI()`](https://www.w3schools.com/jsref/jsref_encodeURI.asp) or [`encodeURIComponent()`](https://www.w3schools.com/jsref/jsref_encodeURIComponent.asp)?
